### ISSUE TITLE
Prepare for v0.9.0

### ISSUE THREAD

**Issue by jollen** [wotcity/wotcity-wot-framework#24]
- [x] Support Coap-to-Websocket Proxy #22 
- [x] Support Websocket-to-Coap Proxy #23 
- [x] Support multiple endpoints #27 
- [x] Major bug fixed: 4aecc103368887c5a0d3ba72a34ea492a3d368ed
- [x] Module exports #28 
- [x] Test suite environment #29 
- [x] Test cases: WebSocket Broker, CoAP Broker, CoAP to WebSocket Broker, and WebSocket to CoAP Broker #29 
- [x] SDK

**Comment by jollen** [comment]
# Module exports

Checkout #28 for the feature ```Module exports```:

```
$ git fetch origin pull/28/head:dev
$ git checkout dev
```

Use CLI to start the CoAP broker server:

```
$ node servers/coap-broker.js 
WoT/CoAP server is listening at coap://192.168.11.34:8000
```

Use a Node.js application to start the CoAP broker server:

```
var server = require('./servers/coap-broker');
server.start();
```

**Comment by jollen** [comment]
## Release Notes

* New feature: CoAP-to-WebSocket Proxy and WebSocket-to-CoAP Proxy servers
* Support multiple endpoints
* Several bugs fixed
* New dev environment: Test Suite and CI
* New SDK toolkits
